server:
  port: 8080
  error:
    include-message: always

spring:
  jackson:
    time-zone: GMT+5
    date-format: yyyy-MM-dd HH:mm:ss

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
    producer:
      bootstrap-servers: localhost:9092



    payment-topic: transaction-topic

  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update
    database-platform : org.hibernate.dialect.MySQL5Dialect
    properties:
      max_allowed_packet: 2000
    generate-ddl: true
